### ISSUE TITLE
Add token verification to LED sign API

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#1015]
basically #442 but in [`api/peripheral_api/routes/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/370ba6774cb7ebe8a732d455304b807609ef91bf/api/peripheral_api/routes/LedSign.js). we don't check tokens atm meaning anyone who knows `curl` or Postman can write whatever they want to our LED sign.

**Comment by c00lme** [comment]
are we able to use a JSON web token for this?

**Comment by c00lme** [comment]
and verify

**Comment by neelp03** [comment]
Yes, that's what we are using for verification. The logic behind JWT verification for the peripheral server was implemented in PR #1027 
Refer to this: https://github.com/SCE-Development/Core-v4/commit/c04343c5da063113e13ebb34ef52c2a48a3f81da
