### ISSUE TITLE
Skeleton Page Loading

### ISSUE THREAD

**Issue by andrewtedi** [SCE-Development/Core-v4#1051]
Something to look into while our UI is being redesigned: [https://www.npmjs.com/package/react-loading-skeleton](https://www.npmjs.com/package/react-loading-skeleton)

We would be able to achieve something like this on our website: 
![image](https://user-images.githubusercontent.com/40414974/160308279-93723835-fd95-41cf-9126-0904bd01e568.png)

**Comment by neelp03** [comment]
#1022

**Comment by andrewtedi** [comment]
Oh, I’ll close this and add the contents to your issue.
