### ISSUE TITLE
Easy Issue: Changing Homepage Picture to Updated Picture from Officers 2021

### ISSUE THREAD

**Issue by seemavora** [SCE-Development/Core-v4#1078]
Change with this picture: https://drive.google.com/file/d/1QGsO7WkfNKPhsXeNz-fH9SmcrLDg8AZg/view?usp=sharing

**Comment by neelp03** [comment]
Consider using WebP format for the images, since it loads 2x faster than png/jpeg

**Comment by Logan-Dang** [comment]
Anyone working on this? I'd like to do this.

**Comment by neelp03** [comment]
All yours
