### ISSUE TITLE
2D Printing

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#125]

**Comment by evanugarte** [comment]
Can look at https://github.com/SCE-Development/Printer for help with connecting to printer

**Comment by evanugarte** [comment]
### 12/23/19 
- We found the printer in Ubuntu options via IP.
- We selected the LaserJet option for type of printer.
- We were able to print with ctrl + P on chrome
- We were able to print with `lp <filename>.pdf` successfully **after** setting the printer to default.

**Comment by evanugarte** [comment]
### 12/31/19
- [Save a file to mongodb](https://stackoverflow.com/questions/13907509/how-do-i-save-a-file-to-mongodb/13923749) with a timestamp e.g. `1577784561719.pdf`
- send `1577784561719` over through the API as a HTTP URL parameter/proto field
- Grab the name in python like 
```py
import os
os.system(f'lp {file}')
```

**Comment by jerrylee17** [comment]
Can this be closed @ThaiQ @evanugarte

**Comment by jerrylee17** [comment]
2D works
