### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#127]

**Comment by evanugarte** [comment]
We need to improve our UI from this:
![image](https://user-images.githubusercontent.com/36345325/71455110-6db61700-2748-11ea-829a-9f6adad45614.png)

**Comment by okjennifer** [comment]
ideally the events page would follow something like this: 

![image](https://user-images.githubusercontent.com/59042514/71455698-0ea5d180-274b-11ea-8517-0959803762a0.png)
