### ISSUE TITLE
Add Doorcode Schema

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#128]
Inside of the [`api/models`](https://github.com/SCE-Development/Core-v4/tree/dev/api/models) directory, we specify how we are to arrange the various collecitons of items we store in MongoDB.

We need to create a new file in that directory that will keep track of doorcodes we enter. Follow the pattern to create a schema, lets call it `DoorCode`.

Things we would like to keep track of are the doorcode value and number of people assigned.

**Comment by evanugarte** [comment]
### 12/05/19 Meeting
- we fixed merge conflicts
