### ISSUE TITLE
Add React Hooks to 2D Printing Page

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#140]
Rewrite the 2D printing page in hooks rather than state

**Comment by ThaiQ** [comment]
Reroute button to 2D-page

![image](https://user-images.githubusercontent.com/18486562/71425379-e33ebc00-2650-11ea-91f9-8196ebc194d1.png)

**Comment by jerrylee17** [comment]
This has been solved with #125
