### ISSUE TITLE
Abstract Server Initialization and Termination for Tests

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#150]
The functions `initializeServer()` and `terminateServer()` pop up in [each test case](https://github.com/SCE-Development/Core-v4/blob/7eb49330115efe0619c97377f7b69382cca2d41d/test/Event.js#L19). The two functions should now be moved to [util/testing-utils/tools.js](https://github.com/SCE-Development/Core-v4/blob/7eb49330115efe0619c97377f7b69382cca2d41d/util/testing-utils/tools.js) to abstract their behavior.

**Comment by ThaiQ** [comment]
Can you work on that Evan? since you know how they work and it will be faster that way. I tried but keep having problems with the variables.

**Comment by evanugarte** [comment]
Good job @nanarboursal !!!!!!
