### ISSUE TITLE
sign up page not working?

### ISSUE THREAD

**Issue by hsorathia** [SCE-Development/Core-v4#1503]
i tried registering for an account (without paying) and nothing seems to be happening.

i checked the console log and i see that there's a 405 posted.

unsure if this is an outage or if i did some incorrect input!

reproduce steps;
1. navigate to sign up page
2. enter in information
3. select any plan (i didn't try with semester)
4. complete captcha
5. submit

please advise :)

also here is what i see btw
network tab;
<img width="509" alt="image" src="https://github.com/user-attachments/assets/e13ac849-b25f-409f-988a-5efd8ba0731e">

normal console + screen;
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/08d311a9-b680-4b9f-827d-cb21c32bbb12">

**Comment by evanugarte** [comment]
ty for bringing this up, this was fixed with https://github.com/SCE-Development/Clark/pull/1486

since this issue was opened, the website was updated and is now the latest version of dev, try again?
i just made an account https://sce.sjsu.edu/register
