### ISSUE TITLE
Editing OfficerBoard

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#157]
Goal: We need to be able to edit our officer manger board (OMB) in src>Pages>OfficerDB

1. Make a new branch out of dev
2. Access the Officer Manager Board (OMG) src>Pages>OfficerDB
4. Make an edit button for each child that trigger a modal
3. Use Modal from Reactstrap, make a modal that:
      -Allow inputs for github, linkedIn, team (this is a drop down), level (drop down)
      -Submit button that do nothing
      -(Even better but not require to): submit button to record and apply the inputs from above

Modal examples:
https://reactstrap.github.io/components/modals/
or in practically any Pages in Corev4

**Comment by evanugarte** [comment]
Closing this unless this is still a thing
