### ISSUE TITLE
Enum for accessLevel and officerRole

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#161]
Access level definition: [here](https://github.com/SCE-Development/Core-v4/blob/c3a6af663f0f402b8766a13b548d25675d05c0c4/api/models/User.js#L60)

Define enum in its own file for both AccessLevel and OfficerRole like below:

```js
export default AccessLevel = 
{
BAN: -2,
PENDING: -1,
// ....
}
```
Example use of enum:

```js
import AccessLevel from '../yourFile.js'
```

**Comment by evanugarte** [comment]
Closed by #177
