### ISSUE TITLE
Render Default Membership Plan

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#163]
By default: it should highlight 'FALL 2019', also render a text says: 'selected' under the card

currently (not highlighted by default but it is default in the api): 
![image](https://user-images.githubusercontent.com/18486562/71425539-08342e80-2653-11ea-91f9-caec22db29b1.png)

**Comment by evanugarte** [comment]
Closed by #197, where the user must pick a plan before continuing.
