### ISSUE TITLE
Add Secure Print option

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#184]
To prevent dummies like @hsorathia from stealing my social security number, we will implement the secure print option. This secure print option is selected by default Standard encryption method should be RSA. See if we can add in AES256 for the server private key. 
Add Secure Print option for [AES256](https://searchsecurity.techtarget.com/definition/Advanced-Encryption-Standard) encryption. 

The Secure Print option will be selected by default. However, there will be a way to turn it off on the printing/profile page for noobs like @nanarboursal.

**Comment by nanarboursal** [comment]
how sweet of you to think about noobs like me, jerry.
