### ISSUE TITLE
Cannot print due to "file too large"

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#195]
Printing page is unable to print due to Error 413: Payload too large. Need to research sending chunks of MIME File.

**Comment by jerrylee17** [comment]
See [this tutorial](https://medium.com/ecmastack/uploading-files-with-react-js-and-node-js-e7e6b707f4ef)

Need separate route for saving the file maybe.

**Comment by ThaiQ** [comment]
Solved
