### ISSUE TITLE
Add Admin Navbar Disabling to Routing.js

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#201]
Adding another optional field that tell which navbar should the component have.

Before [this becomes super long](https://github.com/SCE-Development/Core-v4/blob/2a0c107a7229baf5dd97e34f66ab08ea36052042/src/Routing.js#L121)

[At here](https://github.com/SCE-Development/Core-v4/blob/2a0c107a7229baf5dd97e34f66ab08ea36052042/src/Routing.js#L33)  add an optional field to ```signedInRoutes```
```js
// ...
{
  Component: Login,
  path: '/login',
  allowedIf: !userIsAuthenticated,
  redirect: '/',
  // add the prop below
  disableAdminNavbar: true
}
```

then, the prop for NavbarWrapper can become

```js
enableAdminNavbar={!disableAdminNavbar}
```

**Comment by evanugarte** [comment]
### 3/19 meeting
[`Line 121`](https://github.com/SCE-Development/Core-v4/blob/2a0c107a7229baf5dd97e34f66ab08ea36052042/src/Routing.js#L121) becomes: 
```js
<NavBarWrapper
                    component={Component}
                    enableAdminNavbar={!disableAdminNavbar}
                    {...props}
                  />
```

[`Line 106`](https://github.com/SCE-Development/Core-v4/blob/2a0c107a7229baf5dd97e34f66ab08ea36052042/src/Routing.js#L106) becomes
```js
 ({ path, Component, allowedIf, redirect, disableAdminNavbar }, index) => {
```
