### ISSUE TITLE
Remove All Console.log() Statements

### ISSUE THREAD

**Issue by seemavora** [SCE-Development/Core-v4#204]
This a good link on reference: [Error Handling ](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html).

**Comment by evanugarte** [comment]
Now that we have a utility function to store errors,
https://github.com/SCE-Development/Core-v4/blob/38b5641e9faefa135bf35e54642ab08ea5f5558c/api/util/errorLog-function.js#L12

We can make use of it in [`api/routes`](https://github.com/SCE-Development/Core-v4/tree/dev/api/routes). 

### How to finish this
1. Integrate the function into the various `.catch` blocks in `api/routes`

**Comment by seemavora** [comment]
```js
console.log('hi');
```
