### ISSUE TITLE
Add Transitions to Register Page

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#206]
Similar to [Netflix's sign up page](https://www.netflix.com/signup), we can add transitioning to our webpage.

The first transition can be the membership plan, the second being all the form info we need. This will solve the issue of the page appearing cluttered.

**Comment by evanugarte** [comment]
### 2/3/19
- React transition is legacy code
- let's have components slide in from the left ([example](https://stackoverflow.com/questions/16989585/css-3-slide-in-from-left-transition)?)
- Slide to right if going back

**Comment by hsorathia** [comment]
**2/4/20**
I'm thinking there are two ways to do this right now, one way is to modify the membershipApplication.jsx file where we're swapping out the router transitions, and I've tried modifying this file with less than ideal progress and am lost with this method. I've done some further reading and it looks like I can look at loading in the animations within the components themselves so each component gets an animation as it loads in. This means I would be modifying confirmationpage.js membershipform.js and membershipplan.js instead. I'm not sure if this is the right way to go about it but I think I can do that instead.
Referencing the following links:
- [react view transition example](https://codesandbox.io/s/github/jeremenichelli/react-view-transition-example/tree/master/?from-embed)
- [animate between different views react]( https://css-tricks.com/animating-between-views-in-react/)
- [ccs3 animations](https://www.w3schools.com/css/css3_animations.asp)
- [react transitions with router](https://tylermcginnis.com/react-router-animated-transitions/)

other references:
- [ccs ease in ease out](https://css-tricks.com/ease-out-in-ease-in-out/)
- [sliding react transitions](https://medium.com/front-end-developers/sliding-react-components-4873e232907e)

**Comment by evanugarte** [comment]
### 2/5/20
[This codesandbox example](https://codesandbox.io/s/react-easy-animation-b658i) demonstrates how we can fade things in and out.

It goes like this
`Fade.js`
```jsx
return (
    render && (
      <div
        style={{ animation: `${show ? "fadeIn" : "fadeOut"} 1s` }}
        onAnimationEnd={onAnimationEnd}
      >
        {children}
      </div>
    )
);
```

here, `render` is a boolean that will be set to true when we want to render a certain component. `show` is set to true or false if we want to hide the component.

**Comment by hsorathia** [comment]
```jsx
const componentArray = [
  {
    isShown: membershipState === memberApplicationState.SELECT_MEMBERSHIP_PLAN,
    Component: <MembershipPlan {...appProps} />
   },
  {},
]

// ... larter on that day
componentArray.map((x, index) => {
  return (
    <div {/*handle css tricks here*/}>
      <x.Component />
    </div>
  )
})
```

the css tricks would be like
```jsx
<div style={{ animation: `${x.isShown ? "fadeIn" : "fadeOut"} 1s` }}
```

**Comment by hsorathia** [comment]
https://medium.com/@joethedave/achieving-ui-animations-with-react-the-right-way-562fa8a91935
