### ISSUE TITLE
Add Google Cloud Bucket for Event Photos

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#217]
By adding photos to [a bucket](https://cloud.google.com/storage/docs/json_api/v1/buckets), we will be able to render custom photos that are paired with events. Our website will interact with the bucket on two pages, uploading them in the `EventAdmin` component and rendering them on the event page.

This will be completed after #215.

**Comment by ThaiQ** [comment]
@evanugarte  Should we be using Firebase because we have it running already?

**Comment by evanugarte** [comment]
This is the same thing as #164
