### ISSUE TITLE
Make Setup Script Update printingRPC

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#249]
Make setup.sh script to set up everything

**Comment by evanugarte** [comment]
As of now, all our setup script does is clone the printRPC. This is problematic as what if commits are merged into printRPC later? To pull them in, we should delete and clone the repository [like this](https://github.com/kammce/SJSU-Dev2/blob/05db798c45381f68cae29859640f74ac2255246c/setup#L240)
