### ISSUE TITLE
Printing test

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#252]
Testing for printing

**Comment by evanugarte** [comment]
@jerrylee17 also add a `.then` and `.catch` to your code. Can we schedule a time to meet about it next week?

**Comment by evanugarte** [comment]
![image](https://user-images.githubusercontent.com/36345325/74078273-1066e400-49dd-11ea-9044-3b8d5dddd265.png)

**Comment by evanugarte** [comment]
![image](https://user-images.githubusercontent.com/36345325/74078316-c92d2300-49dd-11ea-9bba-a3892b25d9c9.png)
