### ISSUE TITLE
Add Captcha to Sign Up Page

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#258]
This would be in the [MembershipForm Component](https://github.com/SCE-Development/Core-v4/blob/dev/src/Pages/MembershipApplication/MembershipForm.js), we need to prohibit the user from signing up without completing it.

A good start [may be here](https://medium.com/codeep-io/how-to-use-google-recaptcha-with-react-38a5cd535e0d) by installing `react-google-captcha`.

**Comment by arjohnston** [comment]
I've done this many times in my projects using react-google-captcha. Here's some relevant info below. You can use V2 or V3. I use the V2 checkbox in my projects

Take a look at this boilerplate project I put together that uses it: https://github.com/arjohnston/boilerplates/blob/master/next-express/

Specifically, the API is set up in the server.js:
https://github.com/arjohnston/boilerplates/blob/master/next-express/server.js

The API is used on the contact form:
https://github.com/arjohnston/boilerplates/blob/master/next-express/components/ContactForm/ContactForm.js

And we have the config file holding the keys:
https://github.com/arjohnston/boilerplates/blob/master/next-express/config/config.example.js

You can learn more about recaptcha docs here:
https://developers.google.com/recaptcha/intro

And get started with getting the appropriate keys here:
https://www.google.com/recaptcha/intro/v3.html

**Comment by evanugarte** [comment]
@arjohnston Just saw this, thank you!!!
