### ISSUE TITLE
Redesign AdminNavbar UI

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#263]
As of now, our navbar looks like this:
![image](https://user-images.githubusercontent.com/36345325/74068781-5dcd5c00-49b1-11ea-9de9-e7a6dc143834.png)

It's bland, and we can improve the admin's UI. To mess with the styling, write changes in [`src/Components/Navbar/navbar.css`](https://github.com/SCE-Development/Core-v4/blob/dev/src/Components/Navbar/navbar.css)

The admin navbar can be found in [`src/Components/Navbar/AdminNavbar.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/Components/Navbar/AdminNavbar.js)

**Comment by evanugarte** [comment]
### 2/7 meeting
- The css transition handler can be found [here](https://github.com/SCE-Development/Core-v4/blob/b65b1bea8157d7569228f1fc419adf99c48fa5e5/src/Components/Navbar/navbar.css#L12)
- Hao suggested we make the navbar a darker blue and the text white

**Comment by ThaiQ** [comment]
@evanugarte Could we give Hao this issue?
