### ISSUE TITLE
Enable "The Team" page to a working product

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#265]
Do ```npm run frontend``` in your terminal to run the frontend of the website.

if we navigate to 
![image](https://user-images.githubusercontent.com/18486562/74075050-c0c8ee00-49c5-11ea-86f2-0828d9562741.png) its empty, so lets enable its contents

Go to ```src > pages > TheTeam > TheTeam.js```

**Un-comment all the comments
You will need to ```js import {Media}``` from [reactstrap](https://reactstrap.github.io/components/media/) on [line 2](https://github.com/SCE-Development/Core-v4/blob/b65b1bea8157d7569228f1fc419adf99c48fa5e5/src/Pages/TheTeam/TheTeam.js#L2)** Same as for ```Col, Row,...``` whichever is missing, the terminal will tell you

- - - - - - - - - - - -
Make sure to when you navigate to ![image](https://user-images.githubusercontent.com/18486562/74075050-c0c8ee00-49c5-11ea-86f2-0828d9562741.png) there are contents

- - - - - - - - - -- - -
Notice:  <Ionicon> on [lines...](https://github.com/SCE-Development/Core-v4/blob/b65b1bea8157d7569228f1fc419adf99c48fa5e5/src/Pages/TheTeam/TheTeam.js#L180). **Delete all``` Ionicon``` contents in this file**, we won't be using ionicon anywhere  
**Replace** with [SVG](https://material.io/resources/icons/?style=baseline) for icons of Facebook, LinkedIn, and Github.

**Comment by evanugarte** [comment]
@ThaiQ what are we doing for this one

**Comment by ThaiQ** [comment]
Imma close it.
