### ISSUE TITLE
Add RPCs to 3D Print Remotely

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#269]

**Comment by evanugarte** [comment]
### 2/8 Meeting
- Andrew E. made a python script that takes one arg as a file of type `.stl` and outputs `.gcode`
- The script takes and STL object and rotates it, then slices it and saves it as gcode.
- After doing so, it sends the file to the octopi server and invokes the print

### Plan for Workflow

**Comment by jerrylee17** [comment]
## How to call RPC from backend
1. RPC server must be on
1. Call RPC client from API request in `api/routes`
1. Have an APIFunction in `src/APIFunctions` that calls the endpoint using an axios call
1. Import the APIFunction into your frontend (in `src/Pages`) and call the API function from there.

## Example
#### Backend API Call: `api/routes/print.js`
Bad practice down here. Currently working on making this async, but you get the point -- call the function.
```
router.post('/submit', (req, res) => {
  const { raw, pageRanges, sides, copies, destination } = req.body
  sendPrintRequest(raw, copies, sides, pageRanges, destination)
  return res.sendStatus(OK)
})
```

#### APIFunction: `src/APIFunctions/2DPrinting.js`
```
export async function printPage (data) {
  const status = new PrintApiResponse()
  await axios.post('/api/print/submit', data).catch(() => {
    status.error = true
  })
  return status
}
```

#### Frontend: `Core-v4/src/Pages/2DPrinting/2DPrinting.js`
First Import the function
```
import {
  range,
  parseRange,
  printPage,
  getPagesPrinted
} from '../../APIFunctions/2DPrinting'
```
Send data through
```
var data = {
      raw,
      pageRanges: pageRanges.replace(/\s/g, ''),
      sides,
      copies,
      destination
 }
printPage(data)
```

**Comment by evanugarte** [comment]
@jerrylee17 please please please take your comment and put it somewhere we can save it

**Comment by jerrylee17** [comment]
https://github.com/SCE-Development/Core-v4/wiki/Calling-RPC
