### ISSUE TITLE
Cannot Read Property 'trim' of Undefined

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#271]
Running Overview we see this

![image](https://user-images.githubusercontent.com/36345325/74095153-93ea0900-4aa1-11ea-8868-5ed1520dffe5.png)

@ThaiQ help

**Comment by ThaiQ** [comment]
It needs membership dates
Try adding this to the admin user in mongo 
db.User.insert({
...,
"joinDate" : ISODate("2020-01-23T04:36:21.149Z"), 
"lastLogin" : ISODate("2020-02-09T22:44:41.409Z"), 
"membershipValidUntil" : ISODate("2021-02-01T04:52:53.943Z"), 
})

Full schema sample
{ 
"emailVerified" : false, 
"emailOptIn" : true, 
"active" : true, 
"accessLevel" : 3, 
"pagesPrinted" : 0, 
"password" : "Crap.", 
"firstName" : "thai", 
"middleInitial" : "", 
"lastName" : "quach", 
"email" : "a@a.com", 
"major" : "adwdv", 
"joinDate" : ISODate("2020-01-23T04:36:21.149Z"), 
"lastLogin" : ISODate("2020-02-09T22:44:41.409Z"), 
"membershipValidUntil" : ISODate("2021-02-01T04:52:53.943Z"), 
"__v" : 0, 
"doorCode" : "a"
 }
