### ISSUE TITLE
Creating the "Store" page

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#278]
Navigate to ```src/Pages``` make a new folder calls ```Store``` and navigate into it.
In Store, create ```Store.js```

In Store.js, to initiate React and its basic structures do:
```js
import React from 'react'
export default class Store extends React.Component {
  constructor (props) {
    super(props)

    // Variables
    this.state = {
         yourVariable: "Go In HERE!"
    }

    render() {
         return <div>PAGE CONTENT</div>
    }
  }
}
```
---------------------------------------------------------------------
Go to src/Routing.js

1. Below line [23](https://github.com/SCE-Development/Core-v4/blob/4f16a40b171ce0addea42dc00bfb966a09e1388a/src/Routing.js#L23) import your ```Store.js```
2. At the end of [this list](https://github.com/SCE-Development/Core-v4/blob/4f16a40b171ce0addea42dc00bfb966a09e1388a/src/Routing.js#L92) add your ```Store``` which you imported  with the ```path:'/store'``` 

----------------------------------------------------------------------
You can now navigate to your page with ```localhost:3000/store```

**Comment by ThaiQ** [comment]
![image](https://user-images.githubusercontent.com/18486562/77599721-e309c300-6ec2-11ea-8d92-9dda14815b8a.png)

**Comment by andrewtedi** [comment]
Closed for now, but consider for reopening when we work on the Inventory page
