### ISSUE TITLE
Limit LED sign inputs

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#288]
- Set a limit to maximum brightness at around 75%
- Limit message to 150 maximum characters

**Comment by evanugarte** [comment]
@surabhigupta2029 Will talk about this this week when we meet

**Comment by evanugarte** [comment]
### 2/17 Meeting
- We agreed on flipping the scroll value
- We also agreed on setting a limit for the brightness slider

### How we can do this
- The file containing the website code is [`src/Pages/LedSign/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/Pages/LedSign/LedSign.js)
- To change the sliders range, take a look at [this array](https://github.com/SCE-Development/Core-v4/blob/186731bbe3b061f3eb26d7eb200650720b01b51d/src/Pages/LedSign/LedSign.js#L18)
