### ISSUE TITLE
Use a Class Return Type for APIFunctions/2DPrinting.js

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#291]
![image](https://user-images.githubusercontent.com/36345325/74593845-76a6c480-4fe4-11ea-9416-397c3e42cf3b.png)

Similar to #257, let's use a common return type for `getPagesPrinted` in [`src/APIFunctions/2DPrinting.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/APIFunctions/2DPrinting.js#L66).

1. Define a class called ApiResponse at the top of the file
```js
class ApiResponse {
  constructor () {
    this.error = false
    this.responseData = null
  }
}
```
2. Refactor each function to use this class return type. Here is `printPage` being refactored:
```js
/**
 * Print the page
 * @param {Object} printRequest Encoded file
 * @returns {ApiResponse} Any information related to the API call
 */
export async function printPage (printRequest) {
  let result = new ApiResponse()
  await axios
    .post('/api/print/submit', printRequest)
    .then((response) => {
      result.responseData = response.data
    })
    .catch((error) => {
      result.error = true
      result.response.data = error
    })
  return result
}
```

**Comment by ThaiQ** [comment]
@jerrylee17 have fun
