### ISSUE TITLE
Have Setup.py copy config.example.js to config.js

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#313]
[`setup.py`](https://github.com/SCE-Development/Core-v4/blob/dev/setup.py) allows users to get printingRPC set up with all it's dependencies.

We can also use it to copy `api/config/config.example.js` to `api/config/config.js`

### How to do it
within [this `if` block](https://github.com/SCE-Development/Core-v4/blob/dcdb57fbfd875dcff5fd7c65e616d4564b5c7da7/setup.py#L8), we check the user's OS type.
We can add some logic like:
```py
if user_os == 'Darwin' or user_os == 'Linux':
    setup_status = os.system('./util/setup-scripts/setup.sh')
    # handle copying for mac os or linux here
elif user_os == 'Windows':
    setup_status = os.system('util\setup-scripts\setup.bat')
    # handle copying for windows here
```

Sarah found that [`os.path.exists()`](https://docs.python.org/2/library/os.path.html#os.path.exists) can be used to check if `config.js` is there or not

If it doesn't exist, just copy the file using [`os.system()`](https://www.geeksforgeeks.org/python-os-system-method/)

**Comment by SarahS16** [comment]
```py
 os.path.exists("api/config/config.example.js")
os.system("cp api/config/config.example.js  api/config/config.js")


```
