### ISSUE TITLE
Refactor Officer Schema

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#347]
Schema can be found [here](https://github.com/SCE-Development/Core-v4/blob/c4f8c7c5c77a44e281ee8ce0057580713c2007db/api/models/OfficerManager.js#L4)

Learn how to extend schema from [here](https://stackoverflow.com/questions/18317284/mongoose-extending-schemas)

Schema fields:
- quote : String
- picture : String, require, [default](https://github.com/SCE-Development/Core-v4/blob/c4f8c7c5c77a44e281ee8ce0057580713c2007db/api/constants.js#L9)
- Team: String

Create an enum var [here]()

```js
const teamType = {
  DEVELOPMENT: 'Development',
  PUBLIC_RELATIONS: 'Public Relations',
  ...
  PRESIDENT: "President"
  ...
}
```

**Comment by jeffersonly** [comment]
Question regarding the issue -- What exactly am I trying to extend? 

Based on [this](https://stackoverflow.com/questions/18317284/mongoose-extending-schemas) it looks like it would make the code more complex, uglier, and potentially buggy...

**Comment by evanugarte** [comment]
@jeffersonly We were trying to extend the Schema defined in [`api/models/User.js`](https://github.com/SCE-Development/Core-v4/blob/dev/api/models/User.js). would it be possible to do something like

`OfficerManager.js`
```js
const User = require('./User.js')
const DEFAULT_PHOTO_URL = require('...')

var OfficerSchema = new UserSchema({
  linkedin: {type: String, required: true},
  picture: {type: String, required: true, default: DEFAULT_PHOTO_URL},
  team: {type: String, required: true}
});
```

**Comment by jeffersonly** [comment]
@evanugarte  I don't think it's possible to extend it that way? I'm not sure and don't know how to check if inheritance works. [This](https://stackoverflow.com/questions/18317284/mongoose-extending-schemas) link shows some different ways to do inheritance but as stated before it involves unnecessary complexity, the use of discriminators, or extra dependencies.
