### ISSUE TITLE
LED Sign Message Queuing System

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#350]
As of now, our LED sign in the room can only display one message at a time, which is after a user clicks the "Send" on the page. What if we could send multiple messages to the sign for it to rotate through?

### Goals
- Messages sent from the website to the sign should be stored in a list before the message is written to the sign
- The list of messages should be constantly iterated through after showing each message for a certain time.

#### Advanced Goals
- Could the color of each message send be remembered and rendered?
- Add an expiration date functionality to messages on the sign, so after a certain date they are removed.
- Could you clear the list of messages stored on the sign from the website?

### Getting Started
@jerrylee17 help

### Helpful Links
1. The frontend of the sign page can be found here: [`src/Pages/LedSign/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/Pages/LedSign/LedSign.js)
1. When [this button](https://github.com/SCE-Development/Core-v4/blob/eae6640fa0fa96acc9f4afa163c8b64f38ec6e83/src/Pages/LedSign/LedSign.js#L134) is clicked, it calls [`handleSend()`](https://github.com/SCE-Development/Core-v4/blob/eae6640fa0fa96acc9f4afa163c8b64f38ec6e83/src/Pages/LedSign/LedSign.js#L65)
1. `handleSend()` calls on a function that will then talk to the server, which can be found here: [`src/APIFunctions/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/APIFunctions/LedSign.js) on line 46.
1. The server will receive this call in this file: [`api/routes/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/dev/api/routes/LedSign.js) on line 10.

**Comment by andrewtedi** [comment]
Outdated issue
