### ISSUE TITLE
Simplify Homepage UI

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#368]
What if we have a homepage like this:
[see it here](https://jonasclub.com/Home)
![image](https://user-images.githubusercontent.com/36345325/78596890-626f8e80-7801-11ea-8c9d-fc3f22f8cca4.png)

We can have one photo in the middle with a button

Collage image:
![image](https://user-images.githubusercontent.com/36345325/78597903-2a694b00-7803-11ea-8599-4c4b9fdb1e52.png)

### How to get this done
1. Clear entire front page (except footer)
1. Place the collage image at the top
1. Place text over the image "Software and Computer Engineering Society" with a "who we are" button
1. work with @nanarboursal to redo the navbar to only stretch a limited amount

**Comment by evanugarte** [comment]
What if we have a homepage like this:
[see it here](https://jonasclub.com/Home)
![image](https://user-images.githubusercontent.com/36345325/78596890-626f8e80-7801-11ea-8c9d-fc3f22f8cca4.png)

We can have one photo in the middle with a button

**Comment by seemavora** [comment]
Importing the picture: 

Look at Slideshow.js (in src/components).

**Comment by jerrylee17** [comment]
The design is good, but I don't think it will work on Core-v4. 
1. Current color theme too dark on nav bar. There is no uniform website theme like the page you linked. Therefore, it is difficult to implement something like this that works
2. We don't have that many navbar links so it looks unnecessary
3. Works bad with carousel. Would have to push margins on the side of carousel for this nav bar style to fit, but carousels are designed to take up the whole width

**Comment by evanugarte** [comment]
Ima just say @seemavora resolved this with #510
