### ISSUE TITLE
Add Dependabot to Update Dependencies

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#378]
I am tired of seeing this:
![image](https://user-images.githubusercontent.com/36345325/77124216-80668200-69ff-11ea-9f8a-b683a7cdc2b9.png)

it means that the third party code we rely on to run the website has some sort of security issue. This is bad for us as if it is severe enough, someone may be able to take advantage of our website and do bad things. We can use [Dependabot](https://github.com/marketplace/dependabot-preview) to automatically update our dependencies.

Follow [this tutorial](https://seankilleen.com/2019/07/automagically-update-your-package-dependencies-with-dependabot-for-free/#setting-up-dependabot-for-a-public-github-repository) so we can integrate the tool into Core-v4.
![image](https://user-images.githubusercontent.com/36345325/77124139-4dbc8980-69ff-11ea-8318-8ac930d0eedb.png)

**Comment by realCalvin** [comment]
Added the bot. Should be opening up PRs to update dependencies

**Comment by evanugarte** [comment]
Closed by @realCalvin. Great job!
