### ISSUE TITLE
Fix LedSign Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by hsorathia** [SCE-Development/Core-v4#401]
After going to the LedSign page and attempting to update the sign, the following error appears:
![image](https://user-images.githubusercontent.com/36381158/77717592-1a996d80-6f9e-11ea-835d-dd752b6bc0dc.png)

I have tried adding `await` [here ](https://github.com/SCE-Development/Core-v4/blob/ff2bc18c57a112fafd8500c035249b8407f0b455/api/routes/LedSign.js#L18) and it did not work.

**Comment by evanugarte** [comment]
@hsorathia ill try it out now
