### ISSUE TITLE
Create application that handles dev account creation

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#422]
Create a program that runs in the terminal that automatically creates an account for development purposes.

When we run it, the terminal should look like:

```
Welcome to SCE's dev account creation!
Enter email name:
Enter password:
Enter account priviledge: 
One moment...
Done! You may now sign in with <email they entered> with password <password they entered>.
```

**Comment by hsorathia** [comment]
Create a new object similar to [this] (https://github.com/SCE-Development/Core-v4/blob/c86c7d54542074ec449201dc3d50c91eee9c113c/api/routes/user.js#L58)

**Comment by hsorathia** [comment]
Some packages that are used for command line interfaces using node:
https://www.npmjs.com/package/inquirer
https://www.npmjs.com/package/prompts

**Comment by jerrylee17** [comment]
# Use [readline](https://nodejs.org/api/readline.html)

` npm in stall readine --save`
```
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter email name: ', (answer) => {
    console.log(`Your email is: ${answer}`);
    rl.close();
});
```
Basically r1.question is equivalent to `input('Enter email name')` in python. It takes in 2 parameters: the question and a function of what you'll do with the answer (this is where you would call a separate function to create the account)

An example of the output can be seen below.
![](https://cdn.discordapp.com/attachments/678026288916725810/696274138393739264/unknown.png)
