### ISSUE TITLE
Add API Gateway to Core-v4

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#541]
## What is an API Gateway
It is a service that protects other services by acting as a gateway. Before talking to anything else, you must go thru the gateway first.

### Current SCE architecture:
![image](https://cdn.discordapp.com/attachments/693698635988336691/724767760441278484/SCE_Website_Architecture_2.png)

### Gateway SCE architecture:
![image](https://cdn.discordapp.com/attachments/693698635988336691/726235142196166727/SCE_Website_Architecture_1.png)

## Why do we need it?
1. We will be able to handle all authentication/authorization with tokens in the gateway instead of within each service
1. The school only allows us one domain `sce.sjsu.edu`, so we can't expose all of our services at the same time. We can only expose one port (`443`) and proxy requests to another (`8080`, for example). 

### naive way
defining a route to act as a middleman for each route in a service like:
```js
// take request from browser
router.get('/Printer/printPage', (req, res) => {
  // forward it to one of the blue boxes
  const result = axios.get(
                 'http://localhost:8083/Printer/printPage');
  // return the blue box response back to the user
  res.send(result);
})
```

### More scalable way
define an array to hold all route info:
```js
const { RPC_API_URL, MAIN_ENDPOINTS_URL } = require('../../config/config.json');

const routes = [
  { route: '/api/Printer/printPage', url: RPC_API_URL, protected: true },
  { route: '/api/Events/getEvents', url: MAIN_ENDPOINTS_URL, protected: false }
];
```

map the array to dynamically create "middleman" routes:
```js
routes.map(currentRoute => (
  router.get(currentRoute.route, (req, res) => {
    if (currentRoute.protected) {
      // do the token stuff here
    }
    // forward it to one of the blue boxes
    axios.get(currentRoute.url + currentRoute.route)
      .then(result => {
        res.status(OK).send(result.data);
      })
      .catch(error => {
        res.sendStatus(error.status);        
      });
    // return the blue box response back to the user
    res.send(result);
  })
))
```

**Comment by qsaml** [comment]
again, new coder's question. what visually would the api gateway look like? then it would redirect the user to whichever service he/she would like to go to?
