### ISSUE TITLE
Courses Page Frontend

### ISSUE THREAD

**Issue by IsitaB** [SCE-Development/Core-v4#654]
Make SCE courses accessible to members through Core-v4. md files should be pulled from the Courses repo.

Reference:
<img width="700" alt="Screen Shot 2020-10-11 at 11 37 32 PM" src="https://user-images.githubusercontent.com/50391828/95713091-ca70b880-0c1a-11eb-9c57-3a25b9494506.png">

**Comment by andrewtedi** [comment]
Outdated issue
