### ISSUE TITLE
Add method to count the number of times each API is called

### ISSUE THREAD

**Issue by laurenmacpherson** [SCE-Development/Core-v4#885]
Method will need to send a JSON object in the following format: 
`{
   api_name: string
   Error: bool
   date: string
   Time: string
   UserID: string
   Description: string
}`

This method will need to run when APIs are called.

**Comment by evanugarte** [comment]
We can do this with grafana and prometheus. sound like crazy words but we get something like below:

![image](https://user-images.githubusercontent.com/36345325/141375219-3700755c-ae30-4e2c-a056-ea3971158e36.png)


we can track all of the api calls with the library with minimal work. will bring this up with dev leads later this sem.

**Comment by andrewtedi** [comment]
Outdated issue
