### ISSUE TITLE
Create method to collect user time traffic

### ISSUE THREAD

**Issue by neelp03** [SCE-Development/Core-v4#892]
To collect user time traffic, this method will need to run on all webpages regardless of the permission level. It will also need to send a JSON Object in the specified format below:
```javascript
{
   "PageName" : string,
   "StartTime" : string,
   "EndTime" : string,
   "UserID" : string,
   "SSOID" : string
}
```

**Comment by neel-p1103** [comment]
/src/pages/Login/Login.js 

- "Create an Account" button was modified because original script changed route to membership plan page which prevented the user time traffic features from working properly
- Changes: used a simple <a href> attribute to direct to membership plan page

**Comment by andrewtedi** [comment]
Outdated issue
