### ISSUE TITLE
Consistently merge all Dependabot™️ pull requests into a single PR

### ISSUE THREAD

**Issue by allen-tran** [SCE-Development/Core-v4#913]
Dependabot PR's can get messy and bloating (refer to the image below) but there is a clever solution! 

![image](https://user-images.githubusercontent.com/63386979/145128421-e00c2839-cfd7-4d60-afcd-73419707e45f.png)

## How?
Combining all the PR's would be much more efficient and less tedious when reviewing and merging. 
We can take a look into [this](https://github.com/hrvey/combine-prs-workflow).

**Comment by seemavora** [comment]
This would be a really great change, reviewing individual dependabot PRs was horrible
