### ISSUE TITLE
Optimizes Frontend Docker Builder

### ISSUE THREAD

**Issue by imdominicreed** [SCE-Development/Core-v4#914]
In [`docker/Dockerfile-frontend:13`](https://github.com/SCE-Development/Core-v4/blob/dev/docker/Dockerfile-frontend#L13) we are copying the entire contents of Core-v4 into our frontend container. The only directories we really need are `public`, `util` and `src`. Changing the Dockerfile to follow this will decrease the container size and shorten build times.

**Comment by allen-tran** [comment]
this is legitness
