### ISSUE TITLE
Add Logic for API Key not Being Present

### ISSUE THREAD

**Issue by ajha7** [SCE-Development/Core-v4#922]
# Add Logic for API Key not Being Present

A lot of our code assumes the API key to be valid at runtime.
[`api/cloud_api/routes/Mailer.js`](https://github.com/SCE-Development/Core-v4/blob/66fbb80a6180f8aaf38a2b162a4aaa3f04924616/api/cloud_api/routes/Mailer.js)
is an example, where it imports and uses the keys. We should add logic for checking if
the keys are valid and if they aren't, disable the service.
 
### How to do this
- [x] Change all default config.example.json from `XXXXX...` to some default value like `NOT_SET`
- [x] Add logic for checking if a config.example.json value is equal to `NOT_SET`, and if it isn't, don't run the service.

**Comment by neelp03** [comment]
Added api checks for Google API keys, Discord API keys, Github API keys, and s3Bucket Access keys.
