### ISSUE TITLE
Eslint test not passing due to parsing error

### ISSUE THREAD

**Issue by andrewtedi** [SCE-Development/Core-v4#985]
In #981, Core-v4 checks failed due to the following error in the `npm run lint` test:
![notsupported](https://user-images.githubusercontent.com/40414974/153331467-2b321bc1-bc60-42c2-b42b-15231a884a8b.png)
This [thread](https://stackoverflow.com/questions/69554485/eslint-error-must-use-import-to-load-es-module) may be a good place to start for solving this issue.

**Comment by evanugarte** [comment]
This is still a thing right? I'm assuming so since the PR is closed, let me knwo
